version: '3'
volumes:
  mysqldata:
networks: 
  db_net:
    driver: bridge
services:
  mysqlDB:
    image: mysql:5.7.27
    container_name: mysql-expense
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=expense
    ports:
      - 3306:3306
    networks: 
      - db_net
